export const smoothTransition = {
  duration: 1,
  ease: [0.25, 0.1, 0.25, 1],
};

export const offices = [
  {
    id: 1,
    city: "Riyadh",
    country: "Saudi Arabia",
    address: "Olaya Street, Riyadh 12213, Saudi Arabia",
    phone: "+966 50 578 2607",
    email: "jobs@neorecruits.com",
    hours: "Sun - Thu: 9:00 AM - 6:00 PM",
    lat: 24.7136,
    lng: 46.6753,
    flag: "🇸🇦",
    image: "/locations/riyadh.jpg",
  },
  {
    id: 2,
    city: "Washington D.C.",
    country: "United States",
    address: "1600 Pennsylvania Avenue NW, Washington, DC 20500",
    phone: "+1 929 653 4054",
    email: "jobs@neorecruits.com",
    hours: "Mon - Fri: 9:00 AM - 5:00 PM",
    lat: 38.9072,
    lng: -77.0369,
    flag: "🇺🇸",
    image: "/locations/washington.jpg",
  },
  {
    id: 3,
    city: "London",
    country: "United Kingdom",
    address: "Mayfair, London W1K, United Kingdom",
    phone: "+44 7414 680293",
    email: "jobs@neorecruits.com",
    hours: "Mon - Fri: 9:00 AM - 5:30 PM",
    lat: 51.5074,
    lng: -0.1278,
    flag: "🇬🇧",
    image: "/locations/london.jpg",
  },
  {
    id: 4,
    city: "Islamabad",
    country: "Pakistan",
    address: "Blue Area, Islamabad 44000, Pakistan",
    phone: "+92 302 4909491",
    email: "jobs@neorecruits.com",
    hours: "Mon - Sat: 9:00 AM - 6:00 PM",
    lat: 33.6844,
    lng: 73.0479,
    flag: "🇵🇰",
    image: "/locations/islamabad.jpg",
  },
  {
    id: 5,
    city: "Delhi",
    country: "India",
    address: "Connaught Place, New Delhi, Delhi 110001",
    phone: "+91 72044 83245",
    email: "jobs@neorecruits.com",
    hours: "Mon - Fri: 9:00 AM - 6:00 PM",
    lat: 28.6139,
    lng: 77.209,
    flag: "🇮🇳",
    image: "/locations/delhi.jpg",
  },
];

export const mapConnections = [
  {
    start: { lat: offices[0].lat, lng: offices[0].lng },
    end: { lat: offices[1].lat, lng: offices[1].lng },
  },
  {
    start: { lat: offices[0].lat, lng: offices[0].lng },
    end: { lat: offices[2].lat, lng: offices[2].lng },
  },
  {
    start: { lat: offices[0].lat, lng: offices[0].lng },
    end: { lat: offices[3].lat, lng: offices[3].lng },
  },
  {
    start: { lat: offices[0].lat, lng: offices[0].lng },
    end: { lat: offices[4].lat, lng: offices[4].lng },
  },
];
