export const offices = [
  {
    country: "United Arab Emirates",
    city: "Dubai",
    address: "Level 14, Emirates Towers, Sheikh Zayed Road, Dubai",
    phone: "+971 4 123 4567",
    email: "dubai@neorecruits.com",
    hours: "Sun - Thu: 9:00 AM - 6:00 PM",
    flag: "🇦🇪",
  },
  {
    country: "Saudi Arabia",
    city: "Riyadh",
    address: "KAFD, Building 5.04, Al Aqiq, Riyadh 13519",
    phone: "+966 11 987 6543",
    email: "riyadh@neorecruits.com",
    hours: "Sun - Thu: 9:00 AM - 6:00 PM",
    flag: "🇸🇦",
  },
  {
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    address: "ADGM Square, Al Maryah Island, Abu Dhabi",
    phone: "+971 2 444 5566",
    email: "abudhabi@neorecruits.com",
    hours: "Sun - Thu: 9:00 AM - 6:00 PM",
    flag: "🇦🇪",
  },
  {
    country: "United Kingdom",
    city: "London",
    address: "30 St Mary Axe (The Gherkin), London EC3A 8BF",
    phone: "+44 20 7765 4321",
    email: "london@neorecruits.com",
    hours: "Mon - Fri: 9:00 AM - 5:30 PM",
    flag: "🇬🇧",
  },
  {
    country: "Pakistan",
    city: "Karachi",
    address: "Clifton, Block 9, Karachi 75600",
    phone: "+92 21 1234 5678",
    email: "karachi@neorecruits.com",
    hours: "Mon - Sat: 9:00 AM - 6:00 PM",
    flag: "🇵🇰",
  },
];
