export const jobListings = [
  {
    id: 1,
    title: "Senior Software Engineer",
    company: "Tech Innovations Inc.",
    location: "Dubai, UAE",
    country: "United Arab Emirates",
    city: "Dubai",
    type: "Onsite",
    employmentType: "Full-time",
    salary: "$80k - $120k",
    salaryMin: 80000,
    salaryMax: 120000,
    posted: "2 days ago",
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    industry: "Technology & Digital",
    experience: "Senior (5-10 yrs)",
    description:
      "We're seeking an experienced software engineer to join our dynamic team. You'll work on cutting-edge AI projects and collaborate with top talent in the industry.",
    requirements: ["5+ years experience", "React, Node.js", "AI/ML knowledge"],
    skills: ["React", "Node.js", "TypeScript", "AWS"],
    logo: "/logos/tech-innovations.png",
  },
  {
    id: 2,
    title: "Financial Analyst",
    company: "Global Finance Group",
    location: "Abu Dhabi, UAE",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    type: "Hybrid",
    employmentType: "Full-time",
    salary: "$60k - $90k",
    salaryMin: 60000,
    salaryMax: 90000,
    posted: "3 days ago",
    postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    industry: "Banking & Finance",
    experience: "Mid Level (2-5 yrs)",
    description:
      "Join our finance team and help drive strategic financial decisions. Work with senior leadership on budgeting, forecasting, and financial analysis.",
    requirements: ["3+ years experience", "CFA preferred", "Excel expertise"],
    skills: ["Financial Modeling", "Excel", "Data Analysis"],
    logo: "/logos/global-finance.png",
  },
  {
    id: 3,
    title: "Petroleum Engineer",
    company: "Energy Solutions Ltd.",
    location: "Riyadh, Saudi Arabia",
    country: "Saudi Arabia",
    city: "Riyadh",
    type: "Onsite",
    employmentType: "Contract",
    salary: "$90k - $140k",
    salaryMin: 90000,
    salaryMax: 140000,
    posted: "5 days ago",
    postedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    industry: "Oil & Gas",
    experience: "Senior (5-10 yrs)",
    description:
      "Lead upstream exploration and production operations. Work with cutting-edge technology to optimize oil and gas extraction processes.",
    requirements: [
      "Bachelor's in Petroleum Engineering",
      "5+ years experience",
      "API certifications",
    ],
    skills: ["Reservoir Eng.", "Drilling", "Petrel", "Safety Mgmt"],
    logo: "/logos/energy-solutions.png",
  },
  {
    id: 4,
    title: "Project Manager",
    company: "BuildCorp International",
    location: "Doha, Qatar",
    country: "Qatar",
    city: "Doha",
    type: "Onsite",
    employmentType: "Full-time",
    salary: "$90k - $130k",
    salaryMin: 90000,
    salaryMax: 130000,
    posted: "1 week ago",
    postedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    industry: "Construction",
    experience: "Executive (10+ yrs)",
    description:
      "Lead major infrastructure projects from conception to completion. Manage teams, budgets, and timelines for large-scale construction initiatives.",
    requirements: [
      "PMP certification",
      "10+ years experience",
      "Civil engineering",
    ],
    skills: ["PMP", "Agile", "Budgeting", "Risk Mgmt"],
    logo: "/logos/buildcorp.png",
  },
  {
    id: 5,
    title: "Data Scientist",
    company: "AI Solutions Ltd.",
    location: "Dubai, UAE",
    country: "United Arab Emirates",
    city: "Dubai",
    type: "Remote",
    employmentType: "Full-time",
    salary: "$85k - $125k",
    salaryMin: 85000,
    salaryMax: 125000,
    posted: "4 days ago",
    postedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    industry: "Technology & Digital",
    experience: "Senior (5-10 yrs)",
    description:
      "Apply advanced machine learning techniques to solve complex business problems. Work with large datasets and build predictive models.",
    requirements: ["PhD/Master's", "Python, R", "ML frameworks"],
    skills: ["Python", "Machine Learning", "SQL", "TensorFlow"],
    logo: "/logos/ai-solutions.png",
  },
  {
    id: 6,
    title: "Investment Associate",
    company: "Capital Markets Group",
    location: "Dubai, UAE",
    country: "United Arab Emirates",
    city: "Dubai",
    type: "Hybrid",
    employmentType: "Full-time",
    salary: "$100k - $150k",
    salaryMin: 100000,
    salaryMax: 150000,
    posted: "6 days ago",
    postedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    industry: "Banking & Finance",
    experience: "Mid Level (2-5 yrs)",
    description:
      "Support senior bankers in M&A transactions, IPOs, and corporate finance deals. Analyze market trends and prepare client presentations.",
    requirements: [
      "MBA preferred",
      "2+ years IB experience",
      "Strong analytical skills",
    ],
    skills: ["M&A", "Valuation", "LBO", "Due Diligence"],
    logo: "/logos/capital-markets.png",
  },
  {
    id: 7,
    title: "Electrical Engineer",
    company: "PowerGrid Solutions",
    location: "Abu Dhabi, UAE",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    type: "Onsite",
    employmentType: "Full-time",
    salary: "$75k - $110k",
    salaryMin: 75000,
    salaryMax: 110000,
    posted: "1 day ago",
    postedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    industry: "Electrical & Power",
    experience: "Mid Level (2-5 yrs)",
    description:
      "Design and maintain electrical power systems for critical infrastructure. Work on grid modernization and smart grid technologies.",
    requirements: [
      "Bachelor's in Electrical Engineering",
      "3+ years experience",
      "Power systems expertise",
    ],
    skills: ["AutoCAD", "PLC", "SCADA", "Power Systems"],
    logo: "/logos/powergrid.png",
  },
  {
    id: 8,
    title: "Solar Project Manager",
    company: "GreenTech Renewables",
    location: "Dubai, UAE",
    country: "United Arab Emirates",
    city: "Dubai",
    type: "Hybrid",
    employmentType: "Full-time",
    salary: "$70k - $100k",
    salaryMin: 70000,
    salaryMax: 100000,
    posted: "3 days ago",
    postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    industry: "Renewable Energy",
    experience: "Senior (5-10 yrs)",
    description:
      "Lead solar energy project development from feasibility to commissioning. Manage cross-functional teams and ensure project delivery on time and budget.",
    requirements: [
      "Engineering degree",
      "5+ years solar experience",
      "Project management certification",
    ],
    skills: ["Solar PV", "Project Mgmt", "Renewables", "AutoCAD"],
    logo: "/logos/greentech.png",
  },
];

export const sortOptions = [
  { value: "latest", label: "Latest First" },
  { value: "oldest", label: "Oldest First" },
  { value: "salary-high", label: "Salary: High to Low" },
  { value: "salary-low", label: "Salary: Low to High" },
  { value: "relevance", label: "Relevance" },
];
